version: '3.9'

services:

  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080
    depends_on:
      - postgres-server


  postgres-server:
    image: postgres
    container_name: some-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - postgres-server
    ports:
      - "4000:80"

